// Initial seed data for FinTrack

const now = new Date();
const currentYear = now.getFullYear();
const currentMonth = String(now.getMonth() + 1).padStart(2, '0');

export const INITIAL_TRANSACTIONS = [
  // Current month transactions (Income = ₹80,000, Expenses = ₹42,500)
  {
    id: 'tx-1',
    title: 'Swiggy Food Delivery',
    amount: 500,
    type: 'expense',
    category: 'Food & Dining',
    date: `${currentYear}-${currentMonth}-02`,
    paymentMethod: 'UPI',
    notes: 'Dinner combo with dessert',
  },
  {
    id: 'tx-2',
    title: 'Apartment Rent',
    amount: 18000,
    type: 'expense',
    category: 'Rent & Housing',
    date: `${currentYear}-${currentMonth}-01`,
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly flat rent paid to landlord',
  },
  {
    id: 'tx-3',
    title: 'TechCorp Salary',
    amount: 75000,
    type: 'income',
    category: 'Salary',
    date: `${currentYear}-${currentMonth}-01`,
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly payroll deposit',
  },
  {
    id: 'tx-4',
    title: 'Freelance UI Consultation',
    amount: 5000,
    type: 'income',
    category: 'Freelance',
    date: `${currentYear}-${currentMonth}-03`,
    paymentMethod: 'UPI',
    notes: 'Design review for SaaS dashboard',
  },
  {
    id: 'tx-5',
    title: 'Organic Grocery Mart',
    amount: 6500,
    type: 'expense',
    category: 'Groceries',
    date: `${currentYear}-${currentMonth}-04`,
    paymentMethod: 'Credit Card',
    notes: 'Weekly pantry restocking and vegetables',
  },
  {
    id: 'tx-6',
    title: 'Weekend Dining with Friends',
    amount: 3500,
    type: 'expense',
    category: 'Food & Dining',
    date: `${currentYear}-${currentMonth}-06`,
    paymentMethod: 'Credit Card',
    notes: 'Barbeque dinner outing',
  },
  {
    id: 'tx-7',
    title: 'Zara Fashion & Apparel',
    amount: 4500,
    type: 'expense',
    category: 'Shopping',
    date: `${currentYear}-${currentMonth}-08`,
    paymentMethod: 'Credit Card',
    notes: 'Work wardrobe essentials',
  },
  {
    id: 'tx-8',
    title: 'Fuel & Commute Recharge',
    amount: 3200,
    type: 'expense',
    category: 'Transport',
    date: `${currentYear}-${currentMonth}-10`,
    paymentMethod: 'UPI',
    notes: 'Metro card topup & petrol',
  },
  {
    id: 'tx-9',
    title: 'Electricity & High-Speed WiFi',
    amount: 2800,
    type: 'expense',
    category: 'Utilities',
    date: `${currentYear}-${currentMonth}-12`,
    paymentMethod: 'UPI',
    notes: 'Bescom bill & ACT Fiber broadband',
  },
  {
    id: 'tx-10',
    title: 'Pharmacy & Wellness Checkup',
    amount: 2000,
    type: 'expense',
    category: 'Healthcare',
    date: `${currentYear}-${currentMonth}-14`,
    paymentMethod: 'Debit Card',
    notes: 'Vitamins and routine prescriptions',
  },
  {
    id: 'tx-11',
    title: 'Netflix & Spotify Premium',
    amount: 1500,
    type: 'expense',
    category: 'Entertainment',
    date: `${currentYear}-${currentMonth}-15`,
    paymentMethod: 'Credit Card',
    notes: 'Monthly digital entertainment subscriptions',
  },

  // Past month -1
  {
    id: 'tx-12',
    title: 'TechCorp Salary',
    amount: 72000,
    type: 'income',
    category: 'Salary',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-01`,
    paymentMethod: 'Bank Transfer',
    notes: 'Previous month base salary',
  },
  {
    id: 'tx-13',
    title: 'Stock Dividend Payout',
    amount: 3000,
    type: 'income',
    category: 'Investments',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-10`,
    paymentMethod: 'Bank Transfer',
    notes: 'Quarterly dividend',
  },
  {
    id: 'tx-14',
    title: 'Apartment Rent',
    amount: 18000,
    type: 'expense',
    category: 'Rent & Housing',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-01`,
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly rent',
  },
  {
    id: 'tx-15',
    title: 'Groceries & Household',
    amount: 7200,
    type: 'expense',
    category: 'Groceries',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-05`,
    paymentMethod: 'Credit Card',
    notes: 'Monthly groceries',
  },
  {
    id: 'tx-16',
    title: 'Dining & Cafes',
    amount: 5200,
    type: 'expense',
    category: 'Food & Dining',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-12`,
    paymentMethod: 'UPI',
    notes: 'Dinners & coffees',
  },
  {
    id: 'tx-17',
    title: 'Gadget Accessories',
    amount: 6800,
    type: 'expense',
    category: 'Shopping',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-18`,
    paymentMethod: 'Credit Card',
    notes: 'Mechanical keyboard & mouse',
  },
  {
    id: 'tx-18',
    title: 'Utilities & Bills',
    amount: 3100,
    type: 'expense',
    category: 'Utilities',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-20`,
    paymentMethod: 'UPI',
    notes: 'Power & water',
  },
  {
    id: 'tx-19',
    title: 'Commute & Travel',
    amount: 4000,
    type: 'expense',
    category: 'Transport',
    date: `${currentYear}-${String(Math.max(1, now.getMonth())).padStart(2, '0')}-22`,
    paymentMethod: 'UPI',
    notes: 'Cab rides & transit',
  },
];

export const INITIAL_BUDGETS = [
  {
    id: 'bg-1',
    category: 'Rent & Housing',
    monthlyLimit: 20000,
  },
  {
    id: 'bg-2',
    category: 'Groceries',
    monthlyLimit: 8000,
  },
  {
    id: 'bg-3',
    category: 'Food & Dining',
    monthlyLimit: 5000,
  },
  {
    id: 'bg-4',
    category: 'Shopping',
    monthlyLimit: 6000,
  },
  {
    id: 'bg-5',
    category: 'Utilities',
    monthlyLimit: 3500,
  },
  {
    id: 'bg-6',
    category: 'Transport',
    monthlyLimit: 4000,
  },
  {
    id: 'bg-7',
    category: 'Entertainment',
    monthlyLimit: 2500,
  },
  {
    id: 'bg-8',
    category: 'Healthcare',
    monthlyLimit: 3000,
  },
];

export const INITIAL_SAVINGS_GOALS = [
  {
    id: 'sg-1',
    title: 'Emergency Fund',
    targetAmount: 150000,
    currentAmount: 90000,
    category: 'Security',
    targetDate: '2026-12-31',
    icon: '🛡️',
  },
  {
    id: 'sg-2',
    title: 'Goa Vacation',
    targetAmount: 35000,
    currentAmount: 22500,
    category: 'Travel',
    targetDate: '2026-11-20',
    icon: '🏖️',
  },
  {
    id: 'sg-3',
    title: 'New MacBook Pro M3',
    targetAmount: 180000,
    currentAmount: 110000,
    category: 'Gadgets',
    targetDate: '2027-03-31',
    icon: '💻',
  },
];

export const INITIAL_SETTINGS = {
  userName: 'Mounika',
  accountType: 'Personal Account',
  currency: '₹',
  theme: 'dark', // default modern dark mode
  monthlyIncomeGoal: 100000,
};

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Rent Payment Recorded',
    message: '₹18,000 was recorded for Apartment Rent.',
    timestamp: '2 hours ago',
    type: 'info',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Budget Alert',
    message: 'Food & Dining has reached 80% of its monthly limit.',
    timestamp: '1 day ago',
    type: 'warning',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Savings Milestone',
    message: 'Emergency Fund passed 60% of target!',
    timestamp: '3 days ago',
    type: 'success',
    read: true,
  },
];

export const CATEGORIES = {
  income: ['Salary', 'Freelance', 'Investments', 'Side Hustle', 'Gift', 'Refund', 'Other'],
  expense: [
    'Rent & Housing',
    'Groceries',
    'Food & Dining',
    'Shopping',
    'Utilities',
    'Transport',
    'Entertainment',
    'Healthcare',
    'Education',
    'Travel',
    'Other',
  ],
};

export const PAYMENT_METHODS = ['UPI', 'Bank Transfer', 'Credit Card', 'Debit Card', 'Cash'];
